### ISSUE TITLE
Doesn't work with default bash on macOS Sierra

### ISSUE THREAD

**Issue by strayer** [Moonbase59/makethumbsf6#1]
Just letting you know, since the README doesn't say anything about the bash version on macOS.

```
$ /bin/bash makethumbsf6
makethumbsf6: line 268: ${GALLERY_NAME^}: bad substitution
makethumbsf6 v0.9.4 …
Processing "P1040004.JPG" …
makethumbsf6: line 619: ${ix,,}: bad substitution
```

macOS Sierra 10.11.5 has the following bash version:
```
$ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.
```

It works fine when using bash installed via Homebrew (4.4.12).

**Comment by Moonbase59** [comment]
Thanks for letting us know, and my apologies for the late response. I added a note in the README, under »Requirements«.
